.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/doc.yml
.github/ISSUE_TEMPLATE/features.yml

- Add issue template for bugs, documentation and features

docs: add issue template

---

README.md

I capitalized each word of Heading
example: resources -> Resources

Capitalized first letter of Each Heading

---

README.md
package-lock.json

Closes #29
- The initial setup was missing the `npm install ` command and failed to start the app if you run it like that. Especially if you don't have next.js installed.

make minor changes to the set up documentation to ensure it works

---

README.md

add documentation on how to deploy the app on vercel

---

README.md

made instructions for running the frontend app related to npm only.
we discussed to keep the app `installation and running` simple so we are proceeding with npm only.

docs: updated readme file for frontend running steps

---

README.md

Added instructions for semantic commits
Added instructions for semantic commits as discussed with @ykdojo

doc: added instructions for semantic commits in readme.md file

---

.github/ISSUE_TEMPLATE/doc.yml
.github/ISSUE_TEMPLATE/features.yml
CHANGELOG.md
package.json

Add `label` key to `attributes`
**Before**:
**After**:

fix: missing label key in doc and features issue templates

---

.github/ISSUE_TEMPLATE/dx.yml

added a new template for DX issue

dx: Added a new issue template for DX improvements / refactoring

---

.github/PULL_REQUEST_TEMPLATE.md

dx: remove unnecessary checklist from PR template

---

.commitlintrc.json
.husky/commit-msg
.lintstagedrc.json
package-lock.json
package.json

Added `commitlint` to lint commit messages. It is executed by the newly added `commit-msg` husky git hook that runs on every `git commit` cmd. This change will force contributors to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

dx: add commit-msg git hook to run commitlint

---

.commitlintrc.json
.eslintrc.json
.lintstagedrc.json
.prettierrc.yaml
.vscode/extensions.json
.vscode/settings.json
next.config.js
package-lock.json
package.json
pages/_app.tsx
pages/_document.tsx
pages/api/hello.ts
pages/index.tsx
pages/signin.tsx
pages/signup.tsx
postcss.config.js
tailwind.config.js
tsconfig.json

Run prettier to replace tab with spaces.

refactor: run prettier

---

components/Header.tsx
pages/index.tsx

fixed indentation
fixing prettier format issue in the latest pr

fix: prettier-format-in-latest-pr

---

package-lock.json

#88 introduced some deps that were later removed but the lockfile went out of sync

chore: sync lockfile

---

.editorconfig
.gitignore

- Add JetBrains IDEs configuration folder to gitignore
- Add a universal `editorconfig` file matching the current VSCode config file
This ensures we don't enforce usage of VSCode in the project.
Editorconfig is accepted by many code editors and IDEs out of the box.

dx: add .editorconfig

---

README.md

Adding project board based on this issue [Issue](https://github.com/ykdojo/defaang/issues/97)
Added link for project board on readme

docs: adding project board to read me

---

.gitignore
CODE_OF_CONDUCT.md

- added .env in .gitignore
- fixed the formatting in CODE_OF_CONDUCT

dx: add .env in .gitignore

---

README.md

Make the subheading size consistent with other subheadings

docs: fix Contributing subheading in README

---

CONTRIBUTING.md

Closes #117 
* add project board link to CONTRIBUTING.md
* run format:fix to fix style
none
none

docs: add project board link to CONTRIBUTING.md

---

src/pages/_document.tsx
src/pages/confirm-email.tsx
src/pages/index.tsx
src/pages/signin.tsx
src/pages/signup.tsx
src/pages/submit.tsx

Next.js warns not to use the title tag in the `_document` page instead each page should have its own title tag. The new title tags are inspired by GitHub's document titles.

refactor: use title tag in pages instead of _document

---

package-lock.json
package.json

more info: https://nextjs.org/docs/advanced-features/debugging

dx: add the ability to debug Next.js backend code with Chrome Dev Tools

---

src/lib/types.tsx
src/pages/_app.tsx
src/pages/signin.tsx
src/pages/signup.tsx
src/pages/submit.tsx

- If a user's signed in and is on /signin or /signup, they're redirected to / (index)
- If a user's NOT signed in and is on /submit, they're redirected to signup
Closes #132.

feat: auto redirection based on user's signed in status

---

package-lock.json
package.json
src/pages/submit.tsx

Addresses #108. This is the first PR of a series of PR to close it.

feat: demonstrate react-hook-form

---

package-lock.json
package.json
src/components/Header.tsx

closes #122
Added Header of Tailwind Ui.
Added dependencies: -
'@headlessui/react'
'@heroicons/react/outline'

feat: add header-tailwind-ui

---

src/components/Header.tsx

Closes #148 
- Divided menu into sections with a visual divider
- Added 'Signed in as <email>' item to the top list
The cursor is set to default for a better look, but selecting and copying are still available

feat: improved header menu component

---

src/components/Header.tsx

This is the second of the series of PRs that improves the Sign In/Up and Sign-out flow as discussed in #140.
This PR adds the ability to sign out the user when they click the Sign out button.

feat: sign out functionality

---

src/components/Header.tsx

This is the third PR regarding issue #140. It shows the correct name and email when the user is logged in.
For now, I'm using the first part of the email as a name. In the future, we'd show the user's real name when the backend part is implemented.

feat: show name & email when logged in

---

.eslintrc.json
src/components/Header.tsx
src/lib/types.tsx
src/pages/api/hello.ts

* set `@typescript-eslint/array-type` default to `generic`
> I suggest we use the generic way for better readability
https://github.com/ykdojo/defaang/pull/158#discussion_r962184200

dx: add custom lint rules

---

README.md
src/components/SignIn/Form.tsx
src/components/SignUp/Form.tsx
supabase.sql

- Added a new field for `username` in the signup form
- Removed `placeholder` attributes. (After reading multiple articles I found that they do more harm than help. GitHub too does not use them in their signup form)

feat: add username field in signup form

---

src/components/SignIn/Form.tsx
src/components/SignUp/Form.tsx

- Added a button to show/hide password during signin/signup
- Fixed inconsistent CSS between forms that was making the UI jump up and down when moving between forms
- Removed the unnecessary lock icon from signin submit button

feat: add show-hide password button

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/doc.yml
.github/ISSUE_TEMPLATE/dx.yml
.github/ISSUE_TEMPLATE/features.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/pr-title-checker-config.json

Update issue templates to be in line with the renamed labels

dx: update issue and PR templates

---

CONTRIBUTING.md

docs: Invalid discord server link fixed

---

README.md

docs: Moved Demo link to the top of README.md

---

src/styles/globals.css

feat: Made the scroll behavior to smooth

---

src/components/Features.jsx

feat: explain the launch condition on the landing page

---

src/pages/questions/new.tsx

fix: update questions/new.tsx

---

README.md

docs:  Adding Twitch link

---

src/pages/signin.tsx
src/pages/signup.tsx

fix: hydration error

---

DISCORD_RULES.md

Add a new rule:
> At the end of the day, it's up to the moderators to make decisions to keep this server a safe and inclusive space.

docs: update DISCORD_RULES.md

---

DISCORD_RULES.md
src/components/Header/Header.jsx
src/pages/index.tsx

🛠️ Fixes Issue
Closes https://github.com/ykdojo/defaang/issues/214
Changed CTA text display in Header when the user is signed-in

feat: change CTA text display in Header when user is signed-in

---

README.md

Link to the previous website has been replaced by the new one
Closes #225.

Link for readme updated

---

.github/pr-title-checker-config.json

dx: added perf to allowed title regx

---

next.config.js

Changes images to a more performance friendly type

perf: optimize images

---

CONTRIBUTORS.md

docs: create CONTRIBUTORS.md

---

CONTRIBUTING.md

* Make minor grammar fixes
* Replace all instances of `run `with `call`, shell commands are **run** not **called**
* Include `git add .` method of staging changes in step 6
* Replace the content of step 7. 
repeating step 2 as was previously instructed in step 7 results in an
error; `fatal: A branch named 'branch-name' already exists
`
These changes only affect the **Making changes** section of this document
relates to #223

docs(CONTRIBUTING.md): update contribution guidelines

---

README.md

Closes #237 
Add Gitpod button to the README.md  files for launching defaang workspace rapidly through the browser

DX: Add Gitpod to README.md

---

README.md

#244 
#244 
This PR closes #244 
The link to the tweet has been removed from the readme md file
The only thing removed from the readme md is the link to the tweet

Tweet link removed from readme md file

---

src/components/CallToAction.jsx

Closes: #249 
Add Twitch link on landing page

feat: Add Twitch link on landing page

---

CONTRIBUTORS.md

I submitted 2 interview questions and they got approved

docs: adding a new contributor for an approved interview question

---

src/pages/questions/new.tsx
src/pages/signup.tsx

Closes #271 
I have changed the Router method in the signup file from `push` to `replace`.

solved redirecting back from submission page to Homepage

---

.github/FUNDING.yml

Closes #290 
adds sponsor button with link 
can make sure its working :)

dx: Added link to sponsors page

---

src/components/Header/Header.tsx
tailwind.config.js

Closes #298 
1. added Sign in link to the Header component
I believe it is good UX to have both the sign in and sign up buttons easily available. Totally up to you if you want to include it or not :slightly_smiling_face: Cheers!
https://user-images.githubusercontent.com/2808092/195645613-a9be08b9-5747-469d-87ca-4775e2792a24.mp4

feat: added Sign in link to Header

---

CONTRIBUTORS.md

Added name and GitHub link in CONTRIBUTORS

docs: Update CONTRIBUTORS.md

---

src/components/ProgressBarSection.tsx
src/components/QuestionApprovalProgressBarSection.tsx
src/pages/index.tsx

Closes #262, #270
Add a progress bar

feat: put progress bar at the end of the landing page

---

CONTRIBUTING.md

Closes #311 
I have changed all the github links for the repository

docs: Update links in CONTRIBUTING.md

---

CONTRIBUTING.md

Closes #231 
* Improve making changes section in contribution guidelines.
* This is a continuation of #231

docs(CONTRIBUTING.md): update defaang contribution guidelines
